entrada = input('Digite algo: ')
print('Tipo primitivo: {}'.format(type (entrada)))
print('É numerico? {}'.format(entrada.isnumeric()))
print('É alfanúmerico? {}'.format(entrada.isalnum()))
print('É alfabetico? {}'.format(entrada.isalpha()))
print('Esta maiusculo? {}'.format(entrada.isupper()))
print('Esta minusculo? {}'.format(entrada.islower()))
print('É apenas um espaço em branco? {}'.format(entrada.isspace()))
print('Esta capitalizado? {}'.format(entrada.istitle()))